[package]
name = "image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
libloading = { workspace = true }
